### PR TITLE
Added support for Shelly Dimmer 2

### PR DESCRIPTION
**Pull request by benland**
Added device type dimmer support.
It will allow using brightness functionality in homekit

### CODE REVIEW

**Comment by onfoot** [comment]
Looks pretty good!

Like I said, maybe the device type could be inferred from device's status response so we wouldn't need to change anything in the config, but for now I guess it's okay.

Would you mind sharing what formatter you used on the sources? I'd like to do some automatic formatting on save, but would want to keep the formatting consistent so there are no unnecessary changes in commits in the future.

Oh, and maybe bump just the minor version, not major one. ;)

**Comment by benlaniado** [comment]
@onfoot you are right about the version. I fixed it.
About autodetecting the device, I am not sure I have an easy way of doing it. 
There is a field in the settings called `min_brightness` I can rely on it. or maybe I can make another `/status` call in the initialization and see if there is a `lights[0].brightness` field instead of `relays[0].ison`. otherwise, it is too late. because I want to add `Lightbulb` service instead of `Switch` service. What do you think?

For formatting, I am using autoformatting in my IDE (WebStorm) which is configured to my work settings.

To the project maybe you can add prettier of ESlLint and run it in a pre-commit/pre-push hook

**Comment by onfoot** [comment]
Makes sense to have dimmers as lightbulbs, sure.

To add, the devices could be checked before their respective services are created - that's most of all why I made this plugin as a platform instead of a straight-up accessory. It can add devices at any time, not purely upon launch.

One problem with that would be that if any device happens to not be reachable at the time of homebridge launch, it could be left out - it can happen when everything boots up after a power outage, for example. There would be ways around that, surely, like re-checking the yet unknown device again, or remembering the devices between launches. Sorry, that's just me throwing things out there.

There's an eslint dotfile but I think it's not used recently by my vscode install. At least it doesn't do any formatting on save, which I like personally. But yeah, will probably make a pre-commit hook easily installable and include in the project as well.

**Review by onfoot — APPROVED** [review]

**Comment by onfoot** [comment]
Thanks for the improvements! 0.3.0 is up

**Comment by benlaniado** [comment]
@onfoot I hope I will have time this or the next weekend to add auto detect for the device.

**Pull request merged**
